### ISSUE TITLE
unexpected HTTP response code 500

### ISSUE THREAD

**Issue by unclesamwk** [restic/rest-server#10]
Hey,

i ve Problem.

I installed the restic-server and started it on port 8000.
An init and backup doesnt be work.

debug-output:

CheckConfig()
stat /tmp/restic/ovm4154/config: no such file or directory
POST /ovm4154/keys/93bcd6be459943629ee0e7f21795c9f00d9d2cab7813c19e6a8284e2be977b18
SaveBlob()
open /tmp/restic/ovm4154/keys/93bcd6be459943629ee0e7f21795c9f00d9d2cab7813c19e6a8284e2be977b18: no such file or directory
GET /ovm4154/keys/
ListBlobs()
GET /ovm4154/keys/9212e47add82a13c56944d9c627e06f1f329bc0f40ffa72bda9bd94c20ac8aee
GetBlob()
GET /ovm4154/config
GetConfig()
GET /ovm4154/locks/
ListBlobs()
POST /ovm4154/locks/b2324dbd1842a8ebdef807865be7d69adc44f5a5b16218488387802d0ad5c664
SaveBlob()
GET /ovm4154/locks/
ListBlobs()
GET /ovm4154/locks/b2324dbd1842a8ebdef807865be7d69adc44f5a5b16218488387802d0ad5c664
GetBlob()
GET /ovm4154/index/
ListBlobs()
GET /ovm4154/snapshots/
ListBlobs()
POST /ovm4154/data/8b721003b31308f0bc931d242cb747e11ac1667454e57ab190416c777f7424c2
SaveBlob()
open /tmp/restic/ovm4154/data/8b/8b721003b31308f0bc931d242cb747e11ac1667454e57ab190416c777f7424c2: no such file or directory
POST /ovm4154/data/d9eb46fdbf9083fca170e23c73516b333b225bbd940ffc89aa4a16057d3bfe72
SaveBlob()
open /tmp/restic/ovm4154/data/d9/d9eb46fdbf9083fca170e23c73516b333b225bbd940ffc89aa4a16057d3bfe72: no such file or directory
POST /ovm4154/data/0e6ff305af31380f304b46d1ce97b6f4e106521147f3390f8308a077fab81d29
SaveBlob()
open /tmp/restic/ovm4154/data/0e/0e6ff305af31380f304b46d1ce97b6f4e106521147f3390f8308a077fab81d29: no such file or directory

Do you have any idea?

greetings
Sam

**Comment by bzub** [comment]
I had this problem but I believe it went away when I built restic from it's
master branch instead of using the latest release version.

**Comment by bzub** [comment]
I had this problem but I believe it went away when I built restic from it's master branch instead of using the latest release version.

**Comment by zcalusic** [comment]
Yeah, that this is a good advice. Recently I removed some legacy code and refactored a bit, so you should compile the restic client from master, then it should work properly.

**Comment by zcalusic** [comment]
Or better yet, use the just released version [v0.9.2](https://github.com/restic/rest-server/releases/tag/v0.9.2). And don't forget to upgrade your restic client to also recently released [v0.6.1](https://github.com/restic/restic/releases/tag/v0.6.1) which includes some important performance fixes when used with REST backend.
