### ISSUE TITLE
rest: Server User / Password

### ISSUE THREAD

**Issue by MyLive** [restic/rest-server#103]
Hello @all,

from my Point, it's not a good solution to send the Passwort / User with the URL.
Everyone can see the data in the Process list.

is there any other option ?
like export as variable ... or entering after starting restic ?

Thanks a lot :-),
René

**Comment by wojas** [comment]
Try the `RESTIC_REPOSITORY` env var ([docs](https://restic.readthedocs.io/en/latest/040_backup.html#environment-variables)).

**Comment by MyLive** [comment]
> Try the `RESTIC_REPOSITORY` env var ([docs](https://restic.readthedocs.io/en/latest/040_backup.html#environment-variables)).

I knew the env var's, but none of these fit

**Comment by rawtaz** [comment]
@MyLive Please elaborate on what you mean. The rest-server accepts authentication credentials in the HTTP, it doesn't request that you put them in a URL at all. What makes you think it does, or where are you seeing username and password being put in the URL?

I'm guessing your concern isn't about rest-server, but perhaps you're thinking about how other software such as restic use it (where you specify the username and password in the URL, unless you use the `RESTIC_PASSWORD` instead).
