### ISSUE TITLE
Show a webpage when visited from a browser.

### ISSUE THREAD

**Issue by jtagcat** [restic/rest-server#104]
Docker image ID
---------------------------------
`da93e5693693`

What should rest-server do differently?
---------------------------------------
Health checks! Some way to somehow query the server is not dead nor a zombie. Active gophers only.

What are you trying to do? What is your use case?
-------------------------------------------------
Discovering problems early.

Did rest-server help you today? Did it make you happy in any way?
-----------------------------------------------------------------
I'll opt for a wonderful image instead, by Tadeusz Lakota:
![image](https://user-images.githubusercontent.com/38327267/76940717-abaf7b00-68f2-11ea-8bea-1dbd4136b3b0.png)

**Comment by rawtaz** [comment]
Hey @jtagcat, can you elaborate on this a bit? Off the top of my head you should already be able to do *for example* one of the following to check your server to certain extents:

- Attempt connecting to it over HTTP(S) - if you get a successful connection it's likely up.

- Attempt to use the `/metrics` endpoint to get statistics from it (requires enabling the `--prometheus` flag).

So in summary, what is it you need that you cannot already do?

**Comment by jtagcat** [comment]
Didn't know about the 2nd one and 1st failed due to it not being compatible with Traefik.

**Comment by rawtaz** [comment]
I'm curious, in what way was the first one not compatible with Traefik?

**Comment by jtagcat** [comment]
It was a month ago, but from what I recall is that the rest-server wants either http or https via it's own thing. (tldr) Traefik takes http and makes it https, but since rest-server thought the https was http, there was a problem.

**Comment by jtagcat** [comment]
So I looked in to it and IT MAGICALLY WORKS WITH THE SAME SETTINGS, THE SAME IMAGE AND THE SAME WAY NOW‽

> Attempt connecting to it over HTTP(S) - if you get a successful connection it's likely up.

The test instance URL is https://cn.restic.varukas.ee/
I get a 404, even if it's up. I'll get a 404 if it's down (because it will reach Traefik). Detecting if /monitor is 404 or not is a possible workaround.

I think there should be an option for 'when visited from a browser', show this page, with something 'this is a rest-server instance' and so on. An example of this would be https://rsshub.app/

**Comment by rawtaz** [comment]
Well, in this case you are introducing a frontend that hides the status you get (or don't get) from rest-server.

It seems pretty wrong that you get a 404 when requesting a URL for which the backend isn't responding. I mean, there should be a difference to "cannot contact backend" and "path not found" - how else would you ever be able to distinguish between having asked for a non-existing path and the backend service being down? You can't.

I'd say that your Trafeik should return something like 504 Gateway Timeout instead. Isn't that more accurate?

**Comment by jtagcat** [comment]
Not entirely sure. A nice page for the web browser is not so nice then?

**Comment by rawtaz** [comment]
I'm sorry, I'm not convinced this problem is one that should be fixed in restic this way. Perhaps we should have a nice webpage, but I haven't seen any use case for that yet.

I'll close this for now as I think the solution to your specific problem is a different one, on the other end of the line. Feel free to reply back if you think I'm missing something!
