### ISSUE TITLE
Support subdirectories with --private-repos

### ISSUE THREAD

**Issue by rawtaz** [restic/rest-server#107]
What should rest-server do differently?
---------------------------------------

Currently only one level of username is supported with the `--private-repos` flag, e.g. `http://server/username` is supported but not `http://server/username/foo`, `http://server/username/foo/bar`, etc.

Rest-server should allow *at least* one additional level, e.g. `http://server/username/foo/bar`.

We should at the same time consider if there's a point in, and without too much complexity, possible to, make it accept any number of subdirectories, e.g. `http://server/username/foo/bar/star/har`.

What are you trying to do? What is your use case?
-------------------------------------------------

Example use case: https://github.com/restic/rest-server/issues/76#issuecomment-457291482

**Comment by wojas** [comment]
Supporting `username/repo` would be very helpful, as it would allow one user to have multiple repositories.

I don't really see the use case for more levels than that. It would complicate both the current code (security checks, etc) and any potential future additions that operate on repositories, like for example a status page, a repo data integrity scanner, etc.
