### ISSUE TITLE
404 on file "config", yet it is there

### ISSUE THREAD

**Issue by ncoleman** [restic/rest-server#115]
Output of `rest-server --version` 
---------------------------------

rest-server manually compiled with go1.11.6 on linux/amd64
`cat VERSION` gives 0.9.7

How did you run rest-server exactly?
------------------------------------
```
 rest-server --path /home/nick/backups/thivish --tls --tls-cert wirra.nickcoleman.org.crt --tls-key wirra.nickcoleman.org.key --log rest-server.log
```
Output:
```
Data directory: /home/nick/backups/thivish
Authentication enabled
Private repositories disabled
TLS enabled
Private key: wirra.nickcoleman.org.key
Public key(certificate): wirra.nickcoleman.org.crt
Starting server on :8000
```
Log (Note 404 response):
```
xx.xx.xx.xx  - - [04/Jul/2020:18:57:29 +0800] "HEAD /home/nick/backups/thivish/config HTTP/1.1" 404 19 "" "Go-http-client/1.1"
```
Yet `ls /home/nick/backups/thivish` shows file is present in the requested path:
```
nick@wirra:~/backups/thivish$ ll
total 48
...
-rw-------   1 nick nick  155 Jul  2 17:08 config
...
```
rest-serv is being run as user 'nick' so should have access to the file:
```
$ ps -u nick
  PID TTY          TIME CMD
...
20422 pts/1    00:00:00 rest-server
...
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

rest-server without tls, but with authentication.

Expected behavior
-----------------
restic client should be able to access the repo.

Actual behavior
---------------
rest-server logs a 404. 

restic client reports:
```
Fatal: unable to open config file: <config/> does not exist
Is there a repository at the following location?
rest:https://nick:redact@wirra.nickcoleman.org:8000/home/nick/backups/thivish
```

Steps to reproduce the behavior
-------------------------------
`restic snapshots  ...`

Do you have any idea what may have caused this?
-----------------------------------------------
No.  Weird error message from restic client is some sort of html or xml (`<config/>`), but restic's error msgs can be a bit obtuse sometimes.

Do you have an idea how to solve the issue?
-------------------------------------------
No

Did rest-server help you today? Did it make you happy in any way?
-----------------------------------------------------------------
Yes.  Initial init and subsequent commit worked great.  Great project.

**Comment by MichaelEischer** [comment]
I don't think you should include the `--path /home/nick/backups/thivish` in the REST url. `rest:https://nick:redact@wirra.nickcoleman.org:8000/` should probably work.

**Comment by ncoleman** [comment]
You're right, thank you.  It appears that the path is relative to the one that rest-server is serving even if path starts with '/'.
