### ISSUE TITLE
Make importable

### ISSUE THREAD

**Issue by mholt** [restic/rest-server#12]
Hi, me again. :smile: I'm this 👌 close to having this implemented as a Caddy plugin, which will allow you to add the `restic` directive to your Caddyfile, so you can use HTTPS to transfer files instead of HTTP, without having to worry about certificates.

My motivation is to avoid relying on SFTP which gets slower and slower forever during the transfer, until the transfer takes weeks instead of hours. My hope and expectation is that HTTPS won't do this because it doesn't have the crazy flow control that SSH + SFTP layers on top of TCP's. Or something.

Anyway, one benefit of this being a Caddy plugin is that Caddy can just run indefinitely and keep the 
server going (instead of having to restart it to reload renewed certs), and also serve other websites on the same port too. (One alternative you could do is use [autocert](https://godoc.org/golang.org/x/crypto/acme/autocert) into your program, to get this feature without integrating with Caddy. Autocert requires only a couple lines of code.)

However, in order for me to use this as a library, I need to be able to import it. Specifically, I think I need access to the `setupMux()` function. And if the mux and handlers and stuff could be moved into a non-main package, then I could import it.

So, in summary, I'm requesting:

1. Move as much as possible out of the `main` package so it can be imported
2. Export `setupMux()` so it can be used by other packages in their own handlers

I think I could submit a PR if you're OK with this.

**Comment by fd0** [comment]
The rest-server is developed/maintained by @zcalusic. What do you think?

**Comment by zcalusic** [comment]
Well, it seems like a noble idea. Go for it @mholt, let's see what it would look like!

**Comment by mholt** [comment]
I'll see what I can do tomorrow!

**Comment by fd0** [comment]
For the record: I like this idea a lot! Maybe we need to talk about configuration a bit, so that people are nudged towards configuring authentication (or even making authentication a hard requirement for the plugin). If the REST server is accessible without authentication, attackers can easily just delete the backup.

@zcalusic maybe we should add a large warning for REST servers that are started without basic/digest auth...

**Comment by zcalusic** [comment]
Could you elaborate a bit @fd0? REST server certainly has methods to delete files, yet as all file names are pretty long hashes, it seems it would be a pretty hard task to match their names to delete them?

Although, I'm not against some bolded warning on startup, definitely. Along the lines "you're running UNSECURED setup, for TESTING purposes only" or similar...

**Comment by fd0** [comment]
Sure: When a restic plugin is added to caddy I can imagine that there will be more people who make this plugin accessible over the internet. As soon as attackers know there's a server with the restic REST protocol available, they can just list all data files and remove them one by one. Then the backup is gone.

On the other hand, that may also be the case for our implementation, so maybe we should add a warning there as well. Or even require setting a password or so.

**Comment by bchapuis** [comment]
Hi all, I really like the idea of having automatic HTTPS. However, restic already encrypts the blobs, so HTTPS (which is only required to encrypt the http headers) maybe an overkill. On the longer term, what about using an alternate method for authentication such as JWT (which supports encryption at the level of the token). The JSON format used by JWT might also fit nicely with the JSON format used by restic.

**Comment by fd0** [comment]
@bchapuis thanks for chiming in. I'm sorry, but I must say I disagree: Having easy support for HTTPS such as provided by caddy is enormously valuable in my opinion. restic encrypts all data so confidentiality is not an issue, but protecting the transport via TLS makes passive network analysis much harder and also does not allow tampering with the data in flight. If HTTP basic authentication is used, HTTPS is a must in my opinion.

As for JWT: I don't like this standard at all, and I won't touch it (at least not without coercion). The protocol is way too complex, was designed by a committee (always a bad idea), tried to solve everything and has had a history of really really bad vulnerabilities.

So, no, no JWT for me ;)

**Comment by zcalusic** [comment]
I've also heard only bad stuff about JWT, so I'm not in favour either. While technically double encryption is overhead, it gives some piece of mind. :)

**Comment by zcalusic** [comment]
Here's just one blog entry on the topic, but there are many more to be found around the web: https://paragonie.com/blog/2017/03/jwt-json-web-tokens-is-bad-standard-that-everyone-should-avoid

**Comment by bchapuis** [comment]
@fd0 @zcalusic Glad to hear your opinion on JWT, its always insightful. I never really digged into JWT, so I will be cautious if I have to work with it. Sure HTTPS is absolutely necessary if we rely on basic authentication.

**Comment by mholt** [comment]
@bchapuis

> Hi all, I really like the idea of having automatic HTTPS. However, restic already encrypts the blobs, so HTTPS (which is only required to encrypt the http headers) maybe an overkill.

HTTPS is never overkill! It enables high-bandwidth file transfers because HTTP/2 only works on HTTPS, so HTTPS gives you those multiplexed streams, prevents deep inspection of packets, and protects URLs, headers, etc.

@fd0 @zcalusic I can make it so that basicauth is required, and discard all requests that haven't passed through basicauth successfully.

**Comment by fd0** [comment]
I think that's a good idea. After all, I suspect that many people will use it on the Internet...

**Comment by mholt** [comment]
Great, PR made. It won't allow requests without basicauth.

The Caddy plugin is working nicely. This is my full Caddyfile to run a restic backup server over HTTPS+HTTP/2 (I presume the rest-server doesn't disable HTTP/2):

```
my-home-domain.com:8000

root empty_www  # not strictly needed, but not a bad idea
basicauth / myuser mypass
restic / /mybackups
tls {
	# I use the dns challenge because I don't have
	# ports 80 or 443 open on my home network
	dns cloudflare
}
```

And my backup command is:

```
restic --repo "rest:https://myuser:mypass@my-home-domain.com:8000/reponame" backup ~
```

The Caddy plugin is < 100 lines of code. How would you feel about it being a package in this repo, to keep everything together? You could "own" it, as it were, and publish it to the Caddy website. This would make more sense than me doing it since the core of the rest-server plugin is this repo, all the plugin does is hook in the mux.

**Comment by zcalusic** [comment]
For various reasons, I'd prefer that killing possibility to use unauthenticated access be done completely separately from this issue/PR. It's a semantic change, and I always felt that @bchapuis was on the right track there, trying to basically cover all possible use cases and give a lots of freedom to REST server user. With freedom of course comes responsibility (I always loved that aspect of UNIX 👍). But, please, even if we're both outvoted here for security reasons, let's do that separately, in its own PR, OK?

I'd even like to have separate version for that, so it's easier later to conclude that some feature was killed (yeah, that's what we're basically doing here, killing a feature) in version v0.9.x or something. This change will also require change in documentation, which currently states that you can do whatever you please, but be careful. Suddenly your choices will be limited, and that fact must be properly documented.

Apropos Caddy plugin, if you can fit it in the source and hopfully continue maintaining it as need arise, I don't have problem with that. Especially, if you think that this tree is better to have it inside.

I'm still pending check of the PR, but I'll give you some time to limit the PR to the main context, which is enabling Caddy to work with restic. Feel free to also add plugin code to the repo.

**Comment by mholt** [comment]
To clarify, the requiring of basicauth is implemented in the Caddy plugin,
I didn't make any changes to the rest server except for moving some things
around. Does that change your opinion at all?

**Comment by zcalusic** [comment]
Ah, OK then. You imposed the restriction to Caddy users only. I'll go and check the PR now.

**Comment by mholt** [comment]
Maybe the restic Caddy plugin should be its own repo in the restic organization. I can help maintain it for little things probably (bug fixes). But I can't guarantee I'll implement new enhancements or feature requests.

I've put the plugin code in this gist, along with an example and very basic documentation: https://gist.github.com/mholt/abd794e1a032e4d7167c6948b7559b89

@fd0 Let me know what I can do to help you publish this to the Caddy website after the related PR is merged!

**Comment by fd0** [comment]
Good idea! I've created https://github.com/restic/caddy

**Comment by mholt** [comment]
@fd0 Perhaps you should "own" the plugin at the Caddy website as well? That way you'll control deployments, etc. (Very easy - just a POST request, or pushing a button in your account.) Consider this plugin my gift to you, which helps me. :smile:

**Comment by fd0** [comment]
I can do that, thanks for the contribution!

FYI: You wrote in the README:
> Using restic's "rest" backend instead of the "sftp" backend is likely to provide faster transfer speeds because it avoids a lot of SFTP's flow control problems, where transfers continually get slower and slower forever.

That's not a problem of the sftp protocol (which is not really a great protocol to be honest), but a display error by restic. I'll rework the archiver and the display/progress logic to correct that.

**Comment by mholt** [comment]
I've noticed similar behavior with plain `scp` though, but I'll change the README as soon as I'm not on the road.

**Comment by fd0** [comment]
I'll do that :)

**Comment by mholt** [comment]
@fd0 Caddy 0.10.4 is out and is ready for the restic plugin! :tada:

**Comment by mholt** [comment]
(@fd0 If you tried to register an account today but never got an account confirm email, I've just fixed that -- but let me know and I'll send you the link myself.)

**Comment by fd0** [comment]
So, I still haven't had the time to do this (having a toddler around causes constant interruptions, at least for now). I've roughly looked at the process:
 * We need to open a PR for caddy to correct the URL https://github.com/mholt/caddy/blob/7b5efb5d7581e7c6f04f000369708f5cf25e10f4/caddyhttp/httpserver/plugin.go#L498
 * Register the plugin
 * Make a release so that the website includes it as an option

I've copied this to https://github.com/restic/caddy/issues/1 so we don't need to continue this discussion in a closed issue.
