### ISSUE TITLE
Document the release signature public key

### ISSUE THREAD

**Issue by Strayer** [restic/rest-server#121]
Thank you for the 0.10.0 release! I was wondering what public key is used to sign the checksums of the release files. Right now I'm only checking the hash of the downloaded source file in my Dockerfile, but I'd prefer simply verifying the signature of the `SHA256SUMS.asc` file. I looked around for a bit, but couldn't find anything on which public key is used to sign the file.

What should rest-server do differently?
---------------------------------------

It should document which public key to use to verify release binaries via the `SHA256SUMS.asc`.

What are you trying to do? What is your use case?
-------------------------------------------------

I'm verifying the authenticity of downloaded files on automated Docker builds. Right now, I always have to update the version/git ref, check the source archive for potentially malicious changes and update the source archive hash in the Dockerfile. If I'd have a trusted public key, I'd only need to update the version code and the build should succeed without any further changes because I can (more or less 😉) trust, that the release was done by an actual maintainer.

Sidenote: I'm by no means suggesting that the releases are not trustworthy! This would simply be a much more solid way to build my containers. Apologies if I simply missed the documentation of the public key.

**Comment by fd0** [comment]
Oh, sorry, it's my personal GPG key:

```
pub   rsa4096/91A6868BD3F7A907 2014-11-01 [SC]
      Key fingerprint = CF8F 18F2 8445 7597 3F79  D4E1 91A6 868B D3F7 A907
uid                 [ unknown] Alexander Neumann <alexander@bumpern.de>
sub   rsa4096/D5FC2ACF4043FDF1 2014-11-01 [E]
```

It's the same one we're using for restic's releases. I have ideas to move to something else, like `minisign`, but for now it's GPG.

Does that help?

**Comment by Strayer** [comment]
Hey, thanks for clarifying! I initially created this issue because I think it is helpful to document this in the README.md or something like that, but I wasn't sure how this ties into the restic documentation itself, so I didn't specify this further.

This solves this for me and at least will turn up in searches, so I guess this can be closed for now. Thanks again!
