### ISSUE TITLE
Publish Docker Image

### ISSUE THREAD

**Issue by bclermont** [restic/rest-server#15]
As https://github.com/restic/rest-server/pull/14 was merged, someone from restic team should publish the image to http://hub.docker.com/r/restic

**Comment by zcalusic** [comment]
@fd0, do you own that username on Docker Hub?

**Comment by fd0** [comment]
Yes, I registered it way back. Sorry, I don't have so much time at the moment, I'm swamped with other stuff. Need to check this later (feel free to ping me once in a while though).

**Comment by favadi** [comment]
As we are already using Travis CI, how about configuring it to automatically build, push the docker image if the commit is a tag?

**Comment by DerfOh** [comment]
@favadi that's an awesome idea.

**Comment by zcalusic** [comment]
@fd0, ping!

**Comment by fd0** [comment]
On it

**Comment by fd0** [comment]
Pushed as https://hub.docker.com/r/restic/rest-server/

**Comment by DerfOh** [comment]
Thank you!!! Keep up the amazing work!!!
