### ISSUE TITLE
disabling authentication is broken in the latest published Docker Hub image

### ISSUE THREAD

**Issue by niieani** [restic/rest-server#153]
I saw this bug has been fixed 3 months ago on master, but the latest Docker Hub image is still broken :( Any chance the latest version could be pushed to docker Hub?

Thanks 🙇

**Comment by rawtaz** [comment]
Given that there's been some work done on master very recently (days ago) this will be addressed when it's time, I'm guessing it won't be too far away. I'll close this as there's no action to do here until there's a new release, and that will come when it's ready.

**Comment by rawtaz** [comment]
But we'll make sure to push to master when that happens :)

**Comment by niieani** [comment]
Thanks for the fast response @rawtaz. I found a workaround - put `OPTIONS=--no-auth` as the environment var. Perhaps it would make sense to have CI publish whatever is on master tagged `unstable` or something?

**Comment by wojas** [comment]
This change is not master only, it was changed in [v0.10.0](https://github.com/restic/rest-server/releases/tag/v0.10.0).
