### ISSUE TITLE
Creating sub-repositories does not work

### ISSUE THREAD

**Issue by djmaze** [restic/rest-server#169]
Output of `rest-server --version` 
---------------------------------
3598be715f32 (0.10.0)

How did you run rest-server exactly?
------------------------------------
Via docker with the OPTIONS env variable set to:  `-append-only --private-repos --debug --log /dev/stdout`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
A local docker volume (mounted at `/data`).

Expected behavior
-----------------
From my local machine, I tried to initialize a sub-repository: `restic -r rest:https://user:password@hostname/test/foo/ init`

I expected it to initialize the repository successfully.

Actual behavior
---------------
Got an error message:

`Fatal: create repository at rest:https://user:***@hostname/test/foo/ failed: Fatal: server response unexpected: 404 Not Found (404)`

Initializing a repository directly under `/test` works.

Steps to reproduce the behavior
-------------------------------
1. Create `/data` directory with a `.htpasswd` and a test user
2. Start rest-server as shown above.
3. Run the above init command.

Do you have any idea what may have caused this?
-----------------------------------------------

It seems sub repositories [do not work anymore](https://github.com/restic/rest-server/blob/10dc7a4a8681babad29c8d09579b171290a548b6/changelog/0.10.0_2020-09-13/issue-117), but the README says that it is still possible. Would be good to have a clarification.

Did rest-server help you today? Did it make you happy in any way?
-----------------------------------------------------------------

Looking forward to using this. The `append-only` mode is especially valuable!

**Comment by dimejo** [comment]
This feature was removed with the latest relase v0.10.0 (see #117). It has been readded with #112 but is not part of an official release yet.

**Comment by djmaze** [comment]
Ah, well, should have checked the correct README. Thanks for the clarification!
