### ISSUE TITLE
File open issue

### ISSUE THREAD

**Issue by koen-serry** [restic/rest-server#17]
Hi,

while trying to backup via restic I get the following error on a synology NAS (arm device)

```
POST /data/84da53f26249f5774d99ccafecf244e770a6b37da22faa7ffbb817d8ff641224
SaveBlob()
open /volume1/Public/data/84/84da53f26249f5774d99ccafecf244e770a6b37da22faa7ffbb817d8ff641224: no such file or directory
```

I traced it back to handlers.go:239

```
tf, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_EXCL, 0600)
```
and reason could either be that the folder is not created (it isn't there) or that the permissions can't be set.

Did anyone have a similar issue?

Koen

**Comment by fd0** [comment]
Hey, this is actually a known issue (see #11). Is it possible that you created the repo locally and then served it with the rest-server? In this case, the sub-directories of `data/` are not created, but you can just create them by hand as follows (run it in the repo directory):
```
for i in {0..255}; do mkdir $(printf "data/%02x" $i); done
```
