### ISSUE TITLE
error: unknown flag: --prometheus-no-auth

### ISSUE THREAD

**Issue by JsBergbau** [restic/rest-server#177]
Output of `rest-server --version` 
---------------------------------
rest-server 0.10.0 compiled with go1.15.2 on linux/arm

How did you run rest-server exactly?
------------------------------------
./rest-server --append-only --private-repos --prometheus --prometheus-no-auth --path ../daten

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
rest-server

Expected behavior
-----------------
rest-server starts with no auth for prometheus

Actual behavior
---------------
rest-server prints 2021/12/19 18:39:21 error: unknown flag: --prometheus-no-auth

Steps to reproduce the behavior
-------------------------------
Just run rest-server with the commands above

Do you have any idea what may have caused this?
-----------------------------------------------
I think the released version is too old. However I'm not sure if current code is considered stable to use, so I used the released version.

Do you have an idea how to solve the issue?
-------------------------------------------
Probably create a new stable release.

Did rest-server help you today? Did it make you happy in any way?
-----------------------------------------------------------------
rest-server and restic makes me very happy. I've tried a lot of backupsoftware, but especially with the --append-only option, restic is the best! If it would cost a bit money, I would buy it.

**Comment by jimt** [comment]
You are correct, `--prometheus-no-auth` came after the 0.10.0 release, so for now, you need to build `rest-server` yourself.

(You can use the v0.10.0 tag to check the [README for the last release](https://github.com/restic/rest-server/tree/v0.10.0).)

**Comment by JsBergbau** [comment]
Would be great if there could be an official stable release soon. So other users can also profit.

**Comment by MichaelEischer** [comment]
Closing this issue as the (initial) problem has been resolved.

**Comment by JsBergbau** [comment]
Is there a download page for the current code like for restic at https://beta.restic.net ?

**Comment by rawtaz** [comment]
Not currently, but rest-server builds will be available on that page somewhat soon. But not within a few days or a week or so, so for now build it yourself (super simple).

**Comment by JsBergbau** [comment]
Main problem for me is that I don't know which commit is considered stable for production use. Thats the main reason I've opened this issue. Another reason is that also other users save a lot of time and can just download a recent version and don't have to build their own version. 
If you don't have an automated system build the binaries for various architectures, I'd also be happy to compile for all the architetectures from the previous release and provide them here for download. As also mentioned it is also important for me that other users save time and can profit of the built binaries.

**Comment by rawtaz** [comment]
As I said there will be rest-server builds available on beta.restic.net soon. Until then you can simply use the latest commit on master. Production read or not is a relative definition so you'll just have to relate it to your needs and requirements.

**Comment by JsBergbau** [comment]
> so you'll just have to relate it to your needs and requirements

I mean as stable as the current official release. 

> If in doubt, simply verify the integrity of the snapshots using restic.

When looking at the process of how carefully pullrequests are merged into restic and supposing that the same is done for rest-server, I don't expect that rest server will write any corrupt data.

**Comment by rawtaz** [comment]
I agree :) I would just grab the latest master, build it, and run it :)

**Comment by JsBergbau** [comment]
I've attached a amd64 build of rest-server, hope that helps someone.
```
./rest-server -v
rest-server version rest-server 0.10.0-dev compiled with go1.15.15 on linux/amd64
```

[rest-server_amd64.zip](https://github.com/restic/rest-server/files/7935118/rest-server_amd64.zip)
