### ISSUE TITLE
Compare with minio

### ISSUE THREAD

**Issue by flibustenet** [restic/rest-server#18]
Following #9 i'd like to know how it compare to minio ?
I see that it's dead simple, which is a killer feature, but maybe it's also more efficient ?

**Comment by fd0** [comment]
Minio is a rather complex server implementation. For one, it implements the AWS S3 protocol, which is much more complex than we need. And then it also has support for clustering, which may or may not be needed for your particular use case.

On the other hand the REST protocol is just the minimal thing we need for a restic backend, and can be implemented with just a tiny overhead.

Does that answer your question?

**Comment by flibustenet** [comment]
Thanks to confirm what i thought
