### ISSUE TITLE
Publish Docker images for ARM architecture

### ISSUE THREAD

**Issue by ngosang** [restic/rest-server#185]
It's easy with Docker buildx. I'm doing it in some of my projects with GitHub actions => https://github.com/ngosang/docker-amule/blob/master/.github/workflows/release-docker.yml#L49

Requested archs:
* linux/arm/v7  => arm32
* linux/arm64/v8  => arm64

**Comment by fdw** [comment]
I think this is a duplicate of #125 .

**Comment by MichaelEischer** [comment]
Closed as duplicate.

**Comment by ngosang** [comment]
I built and published my own image with support for 7 architectures. I will maintain it for now, but I would prefer that at some point the official Docker image includes support for multi-arch so I don't have to maintain it. Fell free to copy anything you need from my repository.

* Source code / issues: https://github.com/ngosang/docker-restic-rest-server
* Docker image: https://hub.docker.com/r/ngosang/restic-rest-server
