### ISSUE TITLE
Please put compiled binary files for rest-server in Releases

### ISSUE THREAD

**Issue by chromium58** [restic/rest-server#20]
Hi!

Thank you for restic, it is awesome. I'm now writing deploy with ansible for integrating restic backup in our infrastructure and it will be great to just download already compiled binary file of rest-server instead of compiling it.

Ivan Luckyanov

**Comment by zcalusic** [comment]
Hello @chromium58 and thanks for your comment.

Currently very busy with other stuff, but I will soon add binaries to the releases as you requested. Just a bit of patience...

**Comment by fd0** [comment]
maybe we can use the build container that we use for restic, at https://github.com/restic/builder

**Comment by zcalusic** [comment]
Using the container to do clean builds is a neat idea. Unfortunately, the project you refer to is restic specific. But, I'll do something similar, probably just modify your builder to produce rest-server binaries.

**Comment by fd0** [comment]
I'll have a look if we can simply change the build script and use the same docker build container for both, restic and rest-server.

**Comment by zcalusic** [comment]
@chromium58, the binaries for the latest release have been uploaded. Please check and reopen the issue if you have any trouble.
