### ISSUE TITLE
New release 0.12.0 please

### ISSUE THREAD

**Issue by nogweii** [restic/rest-server#211]
Output of `rest-server --version` 
---------------------------------
Running version `0.11.0` as a docker container on a Synology NAS.

What should rest-server do differently?
---------------------------------------
N/A.

What are you trying to do? What is your use case?
-------------------------------------------------
I am looking to deploy rest-server for my network and tried setting the `$PASSWORD_FILE` option but that is being ignored. Due to the code implementing it not being released yet.

Did rest-server help you today? Did it make you happy in any way?
-----------------------------------------------------------------
Haven't gotten around to implementing it, but I'm excited to start using restic! I felt this was a priority to actually have a place to store the backups. 😄

**Comment by rawtaz** [comment]
Thanks! The release is available here: https://github.com/restic/rest-server/releases/tag/v0.12.0
