### ISSUE TITLE
dns issue?

### ISSUE THREAD

**Issue by pkpowell** [restic/rest-server#24]
restic won't connect to the rest-server via domain name, only via ip.
I get this error:
````
restic -r rest:http://mini.local:8000 backup Documents/
unable to open config file: client.Head: Head http://mini.local:8000/config: dial tcp: lookup mini.local on 192.168.20.1:53: no such host
Is there a repository at the following location?
rest:http://mini.local:8000
````
````
./rest-server --path /Users/phil/backups/restic
rest-server 0.9.4 (v0.9.4-0-g0a0ed9c) compiled with go1.8.3 on darwin/amd64
Data directory: /Users/phil/backups/restic
Authentication disabled
Starting server on :8000
````
`ping mini.local` works fine.
This is on a local network - the server and clients are macs (10.12.6).
192.168.20.1 is my router.
Any ideas?

**Comment by fd0** [comment]
Hm, interesting. Is `mini.local` resolvable via DNS? That's what restic tries. Could you check with `dig mini.local`?

If it's only announced in the Apple/OSX networking multicast thingy (I'm not sure what the name is) then restic will probably not be able to resolve it.

**Comment by pkpowell** [comment]
Oh right, *bonjour/zeroconf* or something - that's probably the case. There's no answer section when I dig anything locally:
````
dig mini.local                                                              
; <<>> DiG 9.8.3-P1 <<>> mini.local
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 48717
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;mini.local.			IN	A

;; AUTHORITY SECTION:
.			418	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2017080300 1800 900 604800 86400

;; Query time: 26 msec
;; SERVER: 192.168.20.1#53(192.168.20.1)
;; WHEN: Thu Aug  3 08:25:59 2017
;; MSG SIZE  rcvd: 103
````

The thing is, it works fine with `sftp:` (forgot to mention that).
````
restic -r sftp:phil@frumious.local:/backups/restic snapshots    
````
So does `ssh` do the resolving for `sftp`?

btw, `frumious.local`is a synology nas. Any chance to get `rest-server`running on one of those?

**Comment by fd0** [comment]
Yeah, for `sftp` backend restic just runs the `ssh` binary, which is apparently able to resolve the name.

You can probably just build the rest-server binary for the NAS, run `go run build.go --goos linux --goarch XX` with `XX` replaced by the architecture of the NAS (`arm`, `arm64`, `386`, `amd64`), then copy the binary and run it.

**Comment by zcalusic** [comment]
This is probably because restic client is statically compiled. That way it doesn't use system resolver, which is the only one that knows about Bonjour.

Compile restic like this:
```
go run build.go --enable-cgo
```

And check that it links to a few of system libraries:
```
ldd ./restic
	linux-vdso.so.1 (0x00007ffddd7f2000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f197182a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f197148b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1971a47000)
```
The example is from my Linux, but you should see something similar on Mac. What you **don't want** to see is:
```
	not a dynamic executable
```

Then check if that fixes your problem.

**Comment by pkpowell** [comment]
awesome, that worked!
thanks everyone.

btw, "ldd" on a mac is "otool -L"

Cheers
Phil
