### ISSUE TITLE
SynoCommunity Package

### ISSUE THREAD

**Issue by jannickfahlbusch** [restic/rest-server#26]
I'd like to build an package for SynoCommunity and therefore for Synology NAS systems.

I saw references in the last issues (https://github.com/restic/rest-server/issues/24#issuecomment-319882539 & #25).

## What needs to be done?
* [ ] Base Package
* [ ] Some sort of UI to set the Repo-path, the SSL-certs and all other parameters

----

Related links:
* [SynoCommunity](https://synocommunity.com/)
* [SynoCommunity's Buildsystem](https://github.com/SynoCommunity/spksrc)
* [Developers HowTo](https://github.com/SynoCommunity/spksrc/wiki/Developers-HOW-TO)

**Comment by fd0** [comment]
Sounds good.

**Comment by wscott** [comment]
Have you tried just using the docker image on Synology? That worked OK for CrashPlan.

**Comment by mannp** [comment]
@jannickfahlbusch Did you manage to make any progress on this as I'd love to have it on my synology devices, especially the older ones soley used as a backup destination.

Sadly only the x86 devices get docker, so for 99% of synologies its of no use.

**Comment by jannickfahlbusch** [comment]
No, sadly not that much. I tried to build a package but discovered then that my NAS supports Docker.

**Comment by wojas** [comment]
I installed rest-server on an old Synology DJ213j with a Marvell Armada-370 PJ4Bv7 (ARM7 with hard float) processor.

I did not create any package for this, but perhaps these instructions will be useful to someone. You will need to have root ssh access and be comfortable with the linux shell. If you have a model that supports Docker, using that will be significantly more convenient than this.

I first compiled `rest-server` (you could probably also just download the linux-arm binary release) with:

```
GOARM=7 go run build.go --goos linux --goarch arm -o rest-server.nas
```

Next I created a new "restic-backup" shared folder, which ends up in `/volume1/restic-backup`, and copied the binary there as `rest-server` (make sure it's executable,  `chmod 755 /volume1/restic-backup/rest-server`).

Create a `.htpasswd` file locally on your computer and copy it to the same folder:

```
htpasswd -B -c .htpasswd your-http-username
```

Create a `/etc/init/rest-server.conf` upstart config with the following contents:

```
# only start this service after the httpd user process has started
start on started httpd-user

# stop the service gracefully if the runlevel changes to 'reboot'
stop on runlevel [06]

# run the scripts as the 'http' user. Running as root (the default) is a bad idea
# CHANGE THIS IF YOU WANT A DIFFERENT USER
setuid http

script
  /volume1/restic-backup/rest-server --listen :8765 --path /volume1/restic-backup --prometheus
end script
```

Change the ownership to match the user you picked in the upstart config en ensure the permissions are correct:

```
chown http /volume1/restic-backup
chmod 755 /volume1/restic-backup
```

Reload the upstart configs and start the service:

```
initctl reload-configuration
initctl start rest-server
```

Now your rest-server should be available on port 8765.

On this NAS, rest-server appears to be CPU-bound for some reason, and the transfer speed maxes out at about 20 MB/s. I also compiled a `restic` binary and ran it there, but it takes more than 15 seconds just to derive the encryption key from your passphrase...

If anyone wants to create a real package out of this, perhaps this is a good starting point: https://github.com/alexandregz/gogs-spk

**Comment by rawtaz** [comment]
@wojas It would be great if you could post this as a [recipe in the forum](https://forum.restic.net/c/recipes/12). It's probably easier to find it there.

**Comment by wojas** [comment]
@rawtaz Thanks for pointing the recipes section out! 

I posted it here:
https://forum.restic.net/t/rest-server-on-an-old-synology-dj213j-nas-arm7-cpu/2597
