### ISSUE TITLE
Question: max body size on a reverse proxy

### ISSUE THREAD

**Issue by donat-b** [restic/rest-server#27]
What is the minimum required body size for rest-server?

Thanks!

**Comment by fd0** [comment]
Interesting question. restic by itself will mostly upload files that are less than 20MiB in size, but it may happen that index files are larger, like ~600MiB in extreme cases...

**Comment by donat-b** [comment]
What most likely to cause such a huge index file?

**Comment by fd0** [comment]
A `prune` process on a large repository.

**Comment by donat-b** [comment]
I think I'm not going to run prune on a non local repository anyway, so it should be fine. :)
I'll update the issue in case of new findings.

**Comment by fd0** [comment]
Nice, thanks!
