### ISSUE TITLE
unable to list pack f8d9161a: unexpected HTTP response code 404

### ISSUE THREAD

**Issue by tscs37** [restic/rest-server#3]
Sometimes the rest-server returns a 404 response code instead of the pack.

The file in question definitely exists:
```
sh-4.2# ls data/main/data/f8 | grep f8d9
f8d9161a32b18bf4dc2a86d31b20881d820c8373fcc4d8031e0a1001664506a6
```

It seems that the server fails to return the file properly at times.

The server is started within systemd, could this be an issue with some limit?

**Comment by zcalusic** [comment]
Hi, and thanks for the report!

Could you please run `find repo_data_directory | wc -l` and report how many files are in your repository?

If there's some kind of system enforced limit, I'd first suspect the number of open file descriptors. Systemd is not the culprit, but it can help fix the issue. You can try adding `LimitNOFILE=262144` in the `[Service]` section, then `systemctl daemon-reload` followed by `systemctl restart rest-server`.

Also, please check file and directory ownership and permissions. It could be that some files are inaccessible to the rest-server user, as defined in the service file.

Do you access the same repo simultaneously from multiple sessions?

**Comment by tscs37** [comment]
Currently the repository contains 8468 files.

The repo was not accessed by several sessions when I tested this, however, the new NOFILE limit seems to have fixed this almost, the number of errors returned has drastically gone down but it's still present.

Ownership and permissions should not be an issue since the rest-server runs inside a container as root.

I think it would be helpful if the rest-server logged such errors or atleast returned some information on the status text.

**Comment by zcalusic** [comment]
Yes, you're right, I will add better logging of errors for the server itself, so we can pinpoint the real cause easier.

With such a small number of files in the repo, it's not likely that number of file descriptors is the problem, although I wouldn't eliminate that possibility completely until we debug this properly.

I will push the needed changes later today, so that you can test it. We should then be able to find the culprit quickly.

Tnx for the info!

**Comment by zcalusic** [comment]
@tscs37, please fetch the latest version, recompile and start the server with --debug flag added. Then you can monitor output in realtime with journalctl -f -u rest-server. I hope we will soon understand where those pesky 404 come from.

I decided to put the error logging under debugging mode, atm. In the future, I plan to add much better logging ala nginx/apache, but this should do for now.

**Comment by tscs37** [comment]
I'm getting some `permission denied` errors, not quite sure why.

It might be an error on my side after all.

**Comment by zcalusic** [comment]
@tscs37, have you fixed the issue? Can I help anyhow?

**Comment by tscs37** [comment]
Sorry for the lack of a response.

I've narrowed the problem down to a NFS mount on the storage side that was not properly setup, all servers were reporting high enough ulimits but the remote did not apply them. Using iSCSI or a mounted QCOW image on the local side has fixed the problem.

**Comment by zcalusic** [comment]
No problem, @tscs37, glad you could fix it. At least we now have better debugging output, to help solve future issues like this.
