### ISSUE TITLE
Auto-generate subfolders

### ISSUE THREAD

**Issue by rawtaz** [restic/rest-server#40]
In the README it's explained that in order to use previously local repos, moving them to your rest-server, you have to run this one-liner: `for i in {0..255}; do mkdir -p $(printf "data/%02x" $i); done`.

Would it not make sense to have rest-server simply create those directories automatically when needed? I imagine there's a way to check it being needed or not just once during a backup run or similar.

**Comment by fd0** [comment]
It's only needed for very old repos, by default restic now creates all subdirs for local repos. So it's not a thing that needs to be present in the rest server.

**Comment by zcalusic** [comment]
Judged by the recently opened https://github.com/restic/restic/issues/1528 issue, it seems that it might be a good idea to retry and create folders in some cases. I'll investigate this and see if I can come with a simple solution that won't slowdown the hot path.
