### ISSUE TITLE
The project does not have a Changelog.

### ISSUE THREAD

**Issue by Mebus** [restic/rest-server#44]
This project currently does not have a Changelog file, but should have one.

Mebus

**Comment by zcalusic** [comment]
I agree. :+1:

I'm doing my best to fill in useful info for releases, but I agree a standard Changelog file would be useful.

We'll come to that...

**Comment by fd0** [comment]
For restic itself I've written a changelog generator called `calens`: https://github.com/restic/calens

**Comment by zcalusic** [comment]
Somehow, it feels like a lot of duplicated, manual, and thus error-prone work. I feel like git should provide most if not all information we need. But, then maybe a human touch will be needed, in the last step. Dunno, we'll see... certainly, this is rather low prio on my todo list.

**Comment by rawtaz** [comment]
Just to chime in, my opinion is that we should use @fd0's calens - it's a great tool to generate a seriously nicely formatted changelog. I'd be happy to make a PR with calens supported changelogs to this project, just have to find a little time for it. Would you mind if we go that route @zcalusic?
