### ISSUE TITLE
Private repos

### ISSUE THREAD

**Issue by MatthewVance** [restic/rest-server#48]
The new private repositories feature add in https://github.com/restic/rest-server/commit/6c846f856ceba09c581e6feb2eb21e5e37bbc6cf and included in release [v0.9.7](https://github.com/restic/rest-server/releases/tag/v0.9.7) does not appear to be documented in the [README](https://github.com/restic/rest-server/blob/master/README.md) or elsewhere.

**Comment by zcalusic** [comment]
Good catch @MatthewVance!

I noticed it soon after the release was already out. :(

We shall remedy it before the next release.

Thanks for the report!

**Comment by MatthewVance** [comment]
Glad to. Thank you for your work on this application and working with the
community to bring in new features.

**Comment by rawtaz** [comment]
Fixed in #52, please merge :)

**Comment by zcalusic** [comment]
Merged, thanks @rawtaz!

**Comment by rawtaz** [comment]
Forgot one key thing in the previous PR..

**Comment by MatthewVance** [comment]
Great. Thank you @rawtaz
