### ISSUE TITLE
Reports and statistics about usage

### ISSUE THREAD

**Issue by Alwaysin** [restic/rest-server#50]
Hello,

it would be nice to have at least a CLI utility to see some metrics, for example I want to have a list of all repos with the date of the last backup/snapshot and the total size it takes on disk repo by repo. Basically a bit like what we can do client by client on client side, but do it on server side with a more global view.

This is crucial info to supervise that we could add to our monitoring station, as backups need to be done frequently and we need to know when it is not the case for whatever reason.

It could be non-specific to rest-server backend but since that's what I use that's what I'm interested in :)

**Comment by mholt** [comment]
@Alwaysin Can you explain your _exact_ needs more clearly? For example, if you have the passwords of the repositories, you can run `restic snapshots` locally on your server to see the snapshots a repo contains. What kind of use case is yours?

**Comment by mholt** [comment]
Closing for now, but feel free to continue discussion if desired.

**Comment by Alwaysin** [comment]
I agree that I wasn't very descriptive about what I was looking for. https://github.com/restic/restic/issues/693 is actually a subset of what I wanted, but I was thinking that server-side would be interesting; with a table listing stats for every repo, it will then be easy to link it to a monitoring system.

**Comment by mholt** [comment]
Is that much different from running `du`?
