### ISSUE TITLE
Integrate with syslog

### ISSUE THREAD

**Issue by Alwaysin** [restic/rest-server#51]
Hi,

The title is pretty self-explanatory: would it be possible to integrate with syslog?

Our logs are growing pretty fast so we need rotation, among other nice features of syslog :)

**Comment by wojas** [comment]
Syslog integration can easily be achieved by piping the output to `logger`, or letting systemd/docker/whatever you use to run your service handle it.

**Comment by fd0** [comment]
I agree, this is better handled by a third-party tool, see https://12factor.net/logs

Implementing log handling (and compression, and rotation, and ...) leads to even more features being requested.

**Comment by Alwaysin** [comment]
Ok thanks for the info! I tried logger but looks like rest-server does not send everything to stdout, I'm talking about logs like:

92.154.9.250 - - [09/Mar/2018:14:59:23 +0100] "HEAD /amwebdev04/config HTTP/1.1" 200 0 "" "Go-http-client/1.1"

so even when piping rest-server to logger, it does not work.
The log are only written to the file when we specify the --log option. So I don't know how to catch them. logger can read a file but not continuously it appears.

I'm not asking for rest-server to handle compression, rotation, etc - this is the purpose of syslog.

**Comment by Alwaysin** [comment]
Nevermind, I've used imfile module of rsyslog:

> module(load="imfile")
> input(type="imfile"
>       File="/home/restic/logs/log"
>       Tag="rest-server:")

Works great :)

**Comment by zcalusic** [comment]
What @wojas suggested can be easily accomplished by `rest-server --log /dev/stdout` and then piping to syslog, or so...

**Comment by rawtaz** [comment]
Seems like this issue can be closed?

**Comment by mholt** [comment]
Yes, I agree; it appears that's a satisfactory solution. :)
