### ISSUE TITLE
Rename --cpuprofile to --cpu-profile

### ISSUE THREAD

**Issue by rawtaz** [restic/rest-server#53]
The `--cpuprofile` flag is inconsistently named, it should be `--cpu-profile` as it's actually two words (like `--append-mode` and `--private-repos`).

I realize people aren't always happy with renames, but we're still at a pre-1.0.0 version and it's better to do it now than later if it's going to be done. Also, this is a flag that probably almost noone ever uses anyway, so it should be fine.

Anyone against?

**Comment by zcalusic** [comment]
You're quite right. The argument was modelled after some pretty vintage golang articles, and looking at what arguments we have today, `--cpu-profile` would be a better choice. Feel free to submit PR.

**Comment by rawtaz** [comment]
Fixed in #56.
