### ISSUE TITLE
Require a htpasswd by default

### ISSUE THREAD

**Issue by wojas** [restic/rest-server#60]
Currently rest-server fails open (does not require auth) if a `.htpasswd` file does not exist or cannot be opened. This is a pretty bad default from a security point of view. 

I suggest that we require the `.htpasswd` file to be present, unless a `-no-auth` flag is set by the user to explicitly tell rest-server it should be wide open.

The downside of adding this is that it would break deployments for existing users that rely on their server being open. I'm not sure if this is a good idea, because it might break unattended backups for users and they might not be monitoring them.

PR #59 contains some comments on this.

**Comment by rawtaz** [comment]
In #59, @fd0 wrote:

> Hm. Shouldn't we make this an error and abort? When users specify a htpasswd file and it cannot be read by the server, isn't that an error which warrants exiting? The intention of the user clearly was that the htpasswd file should be used (it was specified on the command line, after all), so the server probably should not serve the files without any authentication at all.

I don't think there's a way to specify the path to the .htpasswd file specifically, it's just looked for in the persistance path (configurable via `--path`). That part is pretty okay IMO, even though we should probably change `--path` into `--htpasswd-path` and `--storage-path` or similar.

But yes, if the .htpasswd file does not exist or cannot be opened/read in whatever location it's looked for in, we should probably exit with an informative error, unless a switch like `--no-auth` is supplied. It's the sane way for this to work.

I think it's important to keep supporting the use case of no auth though.

So I agree with @wojas and @fd0. Regarding breaking BC I think it's something we can do - the software is not meant to be an official stable 1.0 release yet, and if we make a good release note (related: #44) it should catch most peoples' attention. After all, I think we're all too used to using software regardless of version number, that we expect non-breaking changes a little bit too much. Anyway, I think we should not be afraid of doing this.

**Comment by zcalusic** [comment]
I tend to agree with @rawtaz, we're not 1.0 yet, and this legacy default of not using authentication seems to be problematic. So, if anybody is up to prepare PR, complete with documentation, I'll push it, release new version and properly warn about breaking changes in the release notes. Watch out also for Docker `entrypoint.sh` script, which also deals with this issue in specific ways!

Every time something is discussed several times and there are several workarounds in many places, we have to admit that maybe default behaviour is not sane? :smile:

**Comment by zcalusic** [comment]
To add, this means that I also agree with @wojas proposal. It's important to keep "no-auth" functionality, but from now on require that users explicitly ask for it. From the security standpoint, it's the only right way, IMHO.

**Comment by rawtaz** [comment]
If anyone is up for making those PRs, go ahead. Otherwise I'll do it when I get some time. I guess it's good if whoever starts doing it writes a note in here though, so others don't start work on it at the same time.

**Comment by wojas** [comment]
I can probably do a PR this weekend.

**Comment by rawtaz** [comment]
Go pher it 👍

**Comment by wojas** [comment]
Implemented in PR #61
