### ISSUE TITLE
Repository URLs for --private-repos in README

### ISSUE THREAD

**Issue by moho1** [restic/rest-server#76]
The README currently states rest:https://foo:pass@host:8000/foo/bar as a valid URL for user foo when using --private-repos. But when using such a URL rest-server answers with a 500 Internal Server Error (ignored by restic) first and with a 404 Not Found second on restic init.

We could just fix this error in the documentation or enable such multiple repos for one user. There are some corner cases where this may be interesting to have.

Implementing it for some other separator (e.g. '+') would be pretty easy. I thought I need this, so I already implemented it in https://github.com/moho1/rest-server/tree/multiple_private_repos , but then I found out I don't need it, so I am not opening a pull request here but leave it as discussion. I can happily open a pull request if this is wanted this way.

Implementing it with '/' as separator would be much nicer, but more complex.

**Comment by ririsoft** [comment]
Indeed I fall into the trap until I realized that in a single repository you can backup several distinct things, thus making the use of several repositories per user useless.
However I agree this should be clarified in the readme.

**Comment by ruiztulio** [comment]
I was about to open an issue about this, for me is useful.

In my case we have several customers and each one have severals apps, so I end up with something like:

```
customera\appa.1
customera\appa.2
customera\appa.3

customerb\appb.1
customerb\appb.2
```

I know I can backup all apps in the same repository for a customer, but having it this ways allow us to:

- Delete all backups when app is deprecated/deleted in a single command
- Most of the time when the customer migrate to a different app version we don't need the prev version backups, so it is easier to delete them or upload to amazon glacier
- Sometimes the customer is not our customer, is a customer of another company using our platform and we want to be able to send them the restic repo in case they want it all (not just a single backup that can be gotten easily)

This can be easily done in the command line, but I don't want to have an instance of rest-server per customer (this would be a solution, but not optimal)

**Comment by fpytloun** [comment]
I would also appreciate this feature (nested repos) to have repositories like `customer/app`.
Otherwise when using one repo for all apps might cause issues with locking if backups run in the same time.

**Comment by guggemand** [comment]
If you urlencode the / in the repo name it actually works.

Like rest:https://foo:pass@host:8000/foo%2Fbar

**Comment by ruiztulio** [comment]
I actually made some chenges to make it work as I wanted, if anybody is intrested [here](https://github.com/ruiztulio/rest-server/commit/42c51ba2724e42cf79ae6652aa2d6d56b79c6d15) are the changes, I'm actually new to golang so don't expect it to look very nicely done.

**Comment by rawtaz** [comment]
> I would also appreciate this feature (nested repos) to have repositories like `customer/app`.
> Otherwise when using one repo for all apps might cause issues with locking if backups run in the same time.

Multiple backups can run at the same time, that's not a problem.

**Comment by rawtaz** [comment]
The documentation bug in this issue was just fixed in [b7b5d3](https://github.com/restic/rest-server/commit/b7b5d32538e9abb75fd1a4f25c02bb78fbc4d9ce).

I have opened a new issue for the feature enhancement of allowing more subdirectories, see #107. @ruiztulio can you please create a feature branch out of https://github.com/ruiztulio/rest-server/commit/42c51ba2724e42cf79ae6652aa2d6d56b79c6d15, rebase it on current master and then file a PR for it, referencing #107? Then we can keep working on that there.

**Comment by ruiztulio** [comment]
@rawtaz The PR is here: #108 , sorry for the delay, but these days have been a little cazy

**Comment by demlak** [comment]
> If you urlencode the / in the repo name it actually works.
> 
> Like rest:https://foo:pass@host:8000/foo%2Fbar

Latest Release kills this workaround.. there is a good reason for it.. but it breaks already working setups.. thats bad.
