### ISSUE TITLE
Scoop for rest-server

### ISSUE THREAD

**Issue by copart** [restic/rest-server#84]
Installing and managing restic on Windows is easier with Scoop.  However, cannot find it for rest-server. Any interest?

**Comment by stappersg** [comment]
Please elaborate the reported issue.
Closing this issue is also fine.

**Comment by rawtaz** [comment]
@copart I never use Scoop myself (perhaps I should), but I realize it's a package manager or similar.

The restic project probably won't maintain a package in Scoop, but if you want to make one and are happy to maintain it, then why not :) Will you?

**Comment by rawtaz** [comment]
Closing this because if anyone wants to make *and maintain* a package in other package managers, they're free to do so.
