### ISSUE TITLE
Further prometheus metrics

### ISSUE THREAD

**Issue by adrianschneider94** [restic/rest-server#87]
Hi!

Great work. This is exactly how backups should be.

What I'd wish: Expose not only rather technical data in the '/metrics' endpoint but also information about the backup status. I could then easily setup alarms (e.g. "latest backup is older than 3 days") and be assured everything is fine.

Best wishes
Adrian Schneider

**Comment by wojas** [comment]
If anyone wants to implement this: the best way to get this metric is probably to check for the last timestamp of each repository's snapshot files.

**Comment by rawtaz** [comment]
That's about the only way to do it. `rest-server` can't peek into the data in the repository, nor does it understand the restic "protocol". All it does is shuffle files in a RESTful way, that's all.

**Comment by adrianschneider94** [comment]
Ok, I get that. 

So I think it's probably the better path to write a restic exporter which you hand the connection strings and credentials to the repositories you want to monitor and use restic to get the appropriate metrics from it. Right?

**Comment by rawtaz** [comment]
Yeah, something like that. Would have to think about how to keep those credentials safe.

Personally I wrote a small script/app that just checks the snapshots folder for the last snapshot, I feel that's good enough (it has nothing to do with Prometheus though).

**Comment by adrianschneider94** [comment]
Something like docker secrets or hashicorp vault could handle this. But still in this case -- if you have root access to the host of the exporter you could get the secrets.
I personally think that's ok -- just secure the host properly.

Fine, I think I'll find some spare time for this in the next weeks. And from what I've seen so far, restic seems to make this really easy.
