### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by zx2c4** [restic/rest-server#9]
Was hoping to get some more information (here or in the README) as to why I or anybody would want to use this over the SFTP backend. Does it have better performance characteristics? If so, why? What about compared to OpenSSH-HPN? What does this give you that SFTP doesn't?

**Comment by fd0** [comment]
The idea was to have a server implementation that can be used on very low-end devices, so there's no additional crypto overhead which, depending on the setup and requirements, may not be necessary at all. Think local network with a low-end NAS as the server. restic will properly encrypt all data it sends, so it's mostly about authentication (in a local network setting).

The second point is that the sftp protocol is not really great: Everything needs to be transferred in chunks of 32KiB at most, each packet needs to be acknowledged by the server. The only way to get at least decent speeds is to have multiple packets in flight at once (which is thankfully supported by the protocol and the server implementations), see https://github.com/pkg/sftp/pull/24#issuecomment-59606725 and the following comments for an in-depth explanation.

The REST backend/server just use plain HTTP (or HTTPS with HTTP2 if available), which is just plain TCP and scales MUCH better, especially in high-bandwidth high-latency situations.

**Comment by lyderic** [comment]
Also, I found out that when using sftp, restic calls the 'ssh' command, which is not always present on Windows. So the http rest implementation is a nice alternative, isn't it?
L.

**Comment by fd0** [comment]
I think the question has been answered, therefore I'm closing this issue. Please feel free to leave further comments. Thanks!

**Comment by zcalusic** [comment]
Thank you for asking important questions @zx2c4!

I've now documented this in https://github.com/restic/rest-server/commit/d54a58917651054972e0bf31cc286ebdb113f7f6

@fd0, I borrowed some of your explanation above, hope it's OK. Feel free to adapt/update it, if needed.

**Comment by fd0** [comment]
Sure, completely fine :)
