### ISSUE TITLE
readme fakenews

### ISSUE THREAD

**Issue by trumptarder** [restic/rest-server#91]
Installed as is 'featured' on HackTheBox pentest platform - Registry. 

running the latest binary from the releases page in a docker 
````
root@8b237b0d2749:/# rest-server --path /tmp --no-auth
2019/11/04 01:40:46 error: unknown flag: --no-auth
````

**Comment by fd0** [comment]
Running without authentication is not contained in a release yet, you'll need to build the master branch.

**Comment by rawtaz** [comment]
Please don't use political nonsense words like that in the subject line of this issue.

**Comment by fd0** [comment]
Thanks for the hint @rawtaz, I've retitled the issue. :)
